# Generated by Django 3.2.13 on 2022-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('birth', models.DateField()),
                ('alarm', models.TimeField()),
                ('login', models.IntegerField()),
            ],
        ),
    ]
